title: James Nugent
email: james@jen20.com
description: "James is a software developer working in Bath, England, mostly working on Event Store. He is a connoiseur of cider and old guitars."
baseurl: ""
url: "http://jen20.com"
twitter_username: jen20
github_username:  jen20

# Build settings
markdown: kramdown

kramdown:
        input: GFM
        syntax_highlighter: rouge
